#pragma once

// Generated by tools/reference/create_native_fixtures.py from the locked D0.1
// official OpenMMLab reference. Do not edit by hand.

#include <array>

namespace humanvision::test::fixture {

inline constexpr int kRawWidth = 218;
inline constexpr int kRawHeight = 346;
inline constexpr int kRawStrideBytes = 654;
inline constexpr int kMultiRawWidth = 436;
inline constexpr int kMultiRawHeight = 346;
inline constexpr int kMultiRawStrideBytes = 1308;
inline constexpr int kDetectorResizedWidth = 403;
inline constexpr int kDetectorResizedHeight = 640;
inline constexpr float kDetectorScaleX = 1.84862385F;
inline constexpr float kDetectorScaleY = 1.84971098F;

struct PreprocessSample {
    int x;
    int y;
    std::array<float, 3> normalized_bgr;
};

inline constexpr std::array<PreprocessSample, 5> kPreprocessSamples{{
    PreprocessSample{0, 0, {1.96026146F, 1.60574234F, 1.44404483F}},
    PreprocessSample{100, 100, {2.01254892F, 1.71078432F, 1.52966857F}},
    PreprocessSample{402, 639, {-0.741263568F, -1.02030814F, -1.2616663F}},
    PreprocessSample{403, 100, {0.182483688F, -0.0399159454F, -0.165682048F}},
    PreprocessSample{639, 639, {0.182483688F, -0.0399159454F, -0.165682048F}}
}};

inline constexpr std::array<float, 4> kDetectorBboxXyxy{{0.282142788F, 0.478837848F, 215.671021F, 334.492493F}};
inline constexpr float kDetectorScore = 0.916337073F;

}  // namespace humanvision::test::fixture
