#pragma once

// Generated by tools/reference/create_native_fixtures.py from the locked D0.1
// official OpenMMLab reference. Do not edit by hand.

#include <array>

namespace humanvision::test::fixture {

struct PosePreprocessSample {
    int x;
    int y;
    std::array<float, 3> normalized_rgb;
};

struct PoseJointReference {
    float x_px;
    float y_px;
    float confidence;
};

inline constexpr std::array<float, 4> kPoseBboxXyxy{{0.282142788F, 0.478837848F, 215.671021F, 334.492493F}};
inline constexpr std::array<float, 2> kPoseCenterXy{{107.976585F, 167.485672F}};
inline constexpr std::array<float, 2> kPoseScaleWidthHeight{{313.137787F, 417.517059F}};
inline constexpr std::array<float, 6> kPoseSourceToInputAffine{{0.61314863F, 0.0F, 29.7943058F, -1.31610524e-16F, 0.61314863F, 25.3063927F}};

inline constexpr std::array<PosePreprocessSample, 5> kPosePreprocessSamples{{
    PosePreprocessSample{0, 0, {-2.11790395F, -2.03571439F, -1.80444443F}},
    PosePreprocessSample{96, 128, {-1.19316721F, -1.82563031F, -1.54300654F}},
    PosePreprocessSample{191, 255, {-2.11790395F, -2.03571439F, -1.80444443F}},
    PosePreprocessSample{40, 100, {1.76941514F, 1.86834741F, 2.13455343F}},
    PosePreprocessSample{150, 200, {-1.65553558F, -1.44047618F, -1.21185184F}}
}};

inline constexpr std::array<PoseJointReference, 17> kPoseJoints{{
    PoseJointReference{86.7745514F, 34.5652008F, 0.96018064F},
    PoseJointReference{94.1137161F, 28.0414982F, 1.01338995F},
    PoseJointReference{81.0663071F, 29.6724243F, 1.01066935F},
    PoseJointReference{107.161125F, 32.1188126F, 0.943184018F},
    PoseJointReference{76.1735306F, 36.1961288F, 0.925842941F},
    PoseJointReference{126.732231F, 68.8146515F, 0.723915339F},
    PoseJointReference{82.6972351F, 82.6775208F, 0.80177319F},
    PoseJointReference{165.05899F, 110.403259F, 0.674222887F},
    PoseJointReference{59.0488052F, 118.557892F, 0.763209581F},
    PoseJointReference{169.136307F, 116.926964F, 0.690071702F},
    PoseJointReference{24.7993603F, 134.867157F, 0.931946158F},
    PoseJointReference{152.011581F, 166.670212F, 0.787162185F},
    PoseJointReference{120.208527F, 171.562988F, 0.785732985F},
    PoseJointReference{152.011581F, 244.139191F, 0.848357856F},
    PoseJointReference{90.85186F, 228.645401F, 0.826338887F},
    PoseJointReference{192.784729F, 317.530853F, 0.863256335F},
    PoseJointReference{125.101311F, 296.328827F, 0.821273208F}
}};

}  // namespace humanvision::test::fixture
