from __future__ import annotations

import json
from pathlib import Path

import cv2
import numpy as np
import onnx
from onnx import TensorProto, helper

from tools.reference.common import (
    PROJECT_ROOT,
    REFERENCE_IMAGE,
    relative_path,
    require_locked_reference_assets,
    write_json,
)
from tools.reference.contracts import sha256_file


TESTDATA_DIR = PROJECT_ROOT / "tests" / "testdata"
RAW_IMAGE = TESTDATA_DIR / "d0_1_human_pose.bgr"
MULTI_RAW_IMAGE = TESTDATA_DIR / "d0_2_two_people.bgr"
BACKEND_MODEL = TESTDATA_DIR / "add_one.onnx"
MANIFEST = TESTDATA_DIR / "d0_2_fixtures.json"
CONTRACT_HEADER = TESTDATA_DIR / "d0_2_fixture_contract.h"
D0_3_MANIFEST = TESTDATA_DIR / "d0_3_fixtures.json"
D0_3_CONTRACT_HEADER = TESTDATA_DIR / "d0_3_fixture_contract.h"
DETECTOR_REFERENCE = PROJECT_ROOT / "tests" / "golden" / "d0_1" / "detector_reference.json"
POSE_REFERENCE = PROJECT_ROOT / "tests" / "golden" / "d0_1" / "pose_reference.json"


def cpp_float(value: float) -> str:
    text = f"{value:.9g}"
    if "." not in text and "e" not in text and "E" not in text:
        text += ".0"
    return text + "F"


def write_raw_reference_image() -> tuple[int, int]:
    image = cv2.imread(str(REFERENCE_IMAGE), cv2.IMREAD_COLOR)
    if image is None:
        raise RuntimeError(f"Could not decode reference image: {REFERENCE_IMAGE}")
    height, width = image.shape[:2]
    RAW_IMAGE.write_bytes(image.tobytes(order="C"))
    return width, height


def write_multi_person_image() -> tuple[int, int]:
    image = cv2.imread(str(REFERENCE_IMAGE), cv2.IMREAD_COLOR)
    if image is None:
        raise RuntimeError(f"Could not decode reference image: {REFERENCE_IMAGE}")
    composite = cv2.hconcat([image, image])
    height, width = composite.shape[:2]
    MULTI_RAW_IMAGE.write_bytes(composite.tobytes(order="C"))
    return width, height


def detector_preprocess_contract() -> dict:
    image = cv2.imread(str(REFERENCE_IMAGE), cv2.IMREAD_COLOR)
    if image is None:
        raise RuntimeError(f"Could not decode reference image: {REFERENCE_IMAGE}")
    source_height, source_width = image.shape[:2]
    resize_ratio = min(640.0 / source_width, 640.0 / source_height)
    resized_width = int(source_width * resize_ratio + 0.5)
    resized_height = int(source_height * resize_ratio + 0.5)
    resized = cv2.resize(
        image, (resized_width, resized_height), interpolation=cv2.INTER_LINEAR
    )
    padded = np.full((640, 640, 3), 114, dtype=np.uint8)
    padded[:resized_height, :resized_width] = resized
    mean = np.asarray([103.53, 116.28, 123.675], dtype=np.float32)
    std = np.asarray([57.375, 57.12, 58.395], dtype=np.float32)
    normalized = (padded.astype(np.float32) - mean) / std
    sample_points = ((0, 0), (100, 100), (402, 639), (403, 100), (639, 639))
    return {
        "input_size_width_height": [640, 640],
        "resized_width_height": [resized_width, resized_height],
        "scale_factor_xy": [
            resized_width / source_width,
            resized_height / source_height,
        ],
        "samples": [
            {
                "x": x,
                "y": y,
                "normalized_bgr": [float(value) for value in normalized[y, x]],
            }
            for x, y in sample_points
        ],
    }


def write_backend_fixture() -> None:
    input_info = helper.make_tensor_value_info("input", TensorProto.FLOAT, [1, 2])
    output_info = helper.make_tensor_value_info("output", TensorProto.FLOAT, [1, 2])
    one = helper.make_tensor(
        "one", TensorProto.FLOAT, [1, 2], np.asarray([[1.0, 1.0]], dtype=np.float32)
    )
    graph = helper.make_graph(
        [helper.make_node("Add", ["input", "one"], ["output"])],
        "humanvision_add_one_fixture",
        [input_info],
        [output_info],
        [one],
    )
    model = helper.make_model(
        graph,
        producer_name="HumanVisionSDK D0.2 fixture generator",
        opset_imports=[helper.make_opsetid("", 11)],
    )
    model.ir_version = 8
    onnx.checker.check_model(model)
    onnx.save(model, str(BACKEND_MODEL))


def write_contract_header(
    width: int,
    height: int,
    multi_width: int,
    multi_height: int,
    preprocess: dict,
) -> None:
    detector_reference = json.loads(DETECTOR_REFERENCE.read_text(encoding="utf-8"))
    prediction = detector_reference["predictions"][0]
    samples = ",\n".join(
        "    PreprocessSample{" +
        f"{sample['x']}, {sample['y']}, " +
        "{" + ", ".join(f"{value:.9g}F" for value in sample["normalized_bgr"]) + "}}"
        for sample in preprocess["samples"]
    )
    bbox = ", ".join(f"{value:.9g}F" for value in prediction["bbox_xyxy"])
    header = f"""#pragma once

// Generated by tools/reference/create_native_fixtures.py from the locked D0.1
// official OpenMMLab reference. Do not edit by hand.

#include <array>

namespace humanvision::test::fixture {{

inline constexpr int kRawWidth = {width};
inline constexpr int kRawHeight = {height};
inline constexpr int kRawStrideBytes = {width * 3};
inline constexpr int kMultiRawWidth = {multi_width};
inline constexpr int kMultiRawHeight = {multi_height};
inline constexpr int kMultiRawStrideBytes = {multi_width * 3};
inline constexpr int kDetectorResizedWidth = {preprocess['resized_width_height'][0]};
inline constexpr int kDetectorResizedHeight = {preprocess['resized_width_height'][1]};
inline constexpr float kDetectorScaleX = {preprocess['scale_factor_xy'][0]:.9g}F;
inline constexpr float kDetectorScaleY = {preprocess['scale_factor_xy'][1]:.9g}F;

struct PreprocessSample {{
    int x;
    int y;
    std::array<float, 3> normalized_bgr;
}};

inline constexpr std::array<PreprocessSample, {len(preprocess['samples'])}> kPreprocessSamples{{{{
{samples}
}}}};

inline constexpr std::array<float, 4> kDetectorBboxXyxy{{{{{bbox}}}}};
inline constexpr float kDetectorScore = {prediction['score']:.9g}F;

}}  // namespace humanvision::test::fixture
"""
    CONTRACT_HEADER.write_text(header, encoding="utf-8", newline="\n")


def pose_preprocess_contract() -> dict:
    image = cv2.imread(str(REFERENCE_IMAGE), cv2.IMREAD_COLOR)
    if image is None:
        raise RuntimeError(f"Could not decode reference image: {REFERENCE_IMAGE}")
    pose_reference = json.loads(POSE_REFERENCE.read_text(encoding="utf-8"))
    x1, y1, x2, y2 = pose_reference["input"]["person_bbox_xyxy"]
    center = np.asarray([(x1 + x2) * 0.5, (y1 + y2) * 0.5], dtype=np.float32)
    scale = np.asarray([(x2 - x1) * 1.25, (y2 - y1) * 1.25], dtype=np.float32)
    aspect_ratio = 192.0 / 256.0
    if scale[0] > scale[1] * aspect_ratio:
        scale[1] = scale[0] / aspect_ratio
    else:
        scale[0] = scale[1] * aspect_ratio

    source = np.asarray(
        [
            center,
            center + np.asarray([-scale[0] * 0.5, 0.0], dtype=np.float32),
            center + np.asarray([-scale[0] * 0.5, -scale[0] * 0.5], dtype=np.float32),
        ],
        dtype=np.float32,
    )
    destination = np.asarray(
        [[96.0, 128.0], [0.0, 128.0], [0.0, 32.0]], dtype=np.float32
    )
    affine = cv2.getAffineTransform(source, destination).astype(np.float32)
    warped = cv2.warpAffine(image, affine, (192, 256), flags=cv2.INTER_LINEAR)
    rgb = warped[..., ::-1].astype(np.float32)
    mean = np.asarray([123.675, 116.28, 103.53], dtype=np.float32)
    std = np.asarray([58.395, 57.12, 57.375], dtype=np.float32)
    normalized = (rgb - mean) / std
    sample_points = ((0, 0), (96, 128), (191, 255), (40, 100), (150, 200))
    return {
        "bbox_xyxy": [x1, y1, x2, y2],
        "center_xy": [float(value) for value in center],
        "scale_width_height": [float(value) for value in scale],
        "source_to_input_affine": [float(value) for value in affine.reshape(-1)],
        "samples": [
            {
                "x": x,
                "y": y,
                "normalized_rgb": [float(value) for value in normalized[y, x]],
            }
            for x, y in sample_points
        ],
        "joints": pose_reference["joints"],
    }


def write_d0_3_contract_header(contract: dict) -> None:
    samples = ",\n".join(
        "    PosePreprocessSample{" +
        f"{sample['x']}, {sample['y']}, " +
        "{" + ", ".join(cpp_float(value) for value in sample["normalized_rgb"]) + "}}"
        for sample in contract["samples"]
    )
    joints = ",\n".join(
        "    PoseJointReference{" +
        f"{cpp_float(joint['x_px'])}, {cpp_float(joint['y_px'])}, " +
        f"{cpp_float(joint['confidence'])}" +
        "}"
        for joint in contract["joints"]
    )
    bbox = ", ".join(cpp_float(value) for value in contract["bbox_xyxy"])
    center = ", ".join(cpp_float(value) for value in contract["center_xy"])
    scale = ", ".join(cpp_float(value) for value in contract["scale_width_height"])
    affine = ", ".join(
        cpp_float(value) for value in contract["source_to_input_affine"]
    )
    header = f"""#pragma once

// Generated by tools/reference/create_native_fixtures.py from the locked D0.1
// official OpenMMLab reference. Do not edit by hand.

#include <array>

namespace humanvision::test::fixture {{

struct PosePreprocessSample {{
    int x;
    int y;
    std::array<float, 3> normalized_rgb;
}};

struct PoseJointReference {{
    float x_px;
    float y_px;
    float confidence;
}};

inline constexpr std::array<float, 4> kPoseBboxXyxy{{{{{bbox}}}}};
inline constexpr std::array<float, 2> kPoseCenterXy{{{{{center}}}}};
inline constexpr std::array<float, 2> kPoseScaleWidthHeight{{{{{scale}}}}};
inline constexpr std::array<float, 6> kPoseSourceToInputAffine{{{{{affine}}}}};

inline constexpr std::array<PosePreprocessSample, {len(contract['samples'])}> kPosePreprocessSamples{{{{
{samples}
}}}};

inline constexpr std::array<PoseJointReference, {len(contract['joints'])}> kPoseJoints{{{{
{joints}
}}}};

}}  // namespace humanvision::test::fixture
"""
    D0_3_CONTRACT_HEADER.write_text(header, encoding="utf-8", newline="\n")


def main() -> int:
    require_locked_reference_assets()
    TESTDATA_DIR.mkdir(parents=True, exist_ok=True)
    width, height = write_raw_reference_image()
    multi_width, multi_height = write_multi_person_image()
    write_backend_fixture()
    preprocess = detector_preprocess_contract()
    write_contract_header(width, height, multi_width, multi_height, preprocess)
    pose_contract = pose_preprocess_contract()
    write_d0_3_contract_header(pose_contract)
    write_json(
        MANIFEST,
        {
            "schema_version": 1,
            "raw_image": {
                "filename": RAW_IMAGE.name,
                "source": relative_path(REFERENCE_IMAGE),
                "source_sha256": sha256_file(REFERENCE_IMAGE),
                "sha256": sha256_file(RAW_IMAGE),
                "pixel_format": "BGR24",
                "width": width,
                "height": height,
                "stride_bytes": width * 3,
            },
            "multi_person_raw_image": {
                "filename": MULTI_RAW_IMAGE.name,
                "construction": "two horizontal copies of the locked official reference image",
                "source_sha256": sha256_file(REFERENCE_IMAGE),
                "sha256": sha256_file(MULTI_RAW_IMAGE),
                "pixel_format": "BGR24",
                "width": multi_width,
                "height": multi_height,
                "stride_bytes": multi_width * 3,
            },
            "backend_model": {
                "filename": BACKEND_MODEL.name,
                "sha256": sha256_file(BACKEND_MODEL),
                "opset": 11,
                "input": {"name": "input", "shape": [1, 2], "dtype": "float32"},
                "output": {"name": "output", "shape": [1, 2], "dtype": "float32"},
                "operation": "output = input + [1.0, 1.0]",
            },
            "detector_preprocess": preprocess,
        },
    )
    write_json(
        D0_3_MANIFEST,
        {
            "schema_version": 1,
            "source": "tests/golden/d0_1/pose_reference.json",
            "pose_preprocess": pose_contract,
        },
    )
    print(
        "Wrote native fixtures: "
        f"{RAW_IMAGE}, {MULTI_RAW_IMAGE}, {BACKEND_MODEL}, {CONTRACT_HEADER}, "
        f"{D0_3_CONTRACT_HEADER}, {MANIFEST}, {D0_3_MANIFEST}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
