"""Generate deterministic component documentation from source-owned metadata."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / 'docs/maintenance/GENERATED_COMPONENT_CATALOG.md'
ROOTS = ['runtime', 'modelpacks', 'profiles', 'native/src/core', 'unity/HumanVisionDemo/Assets/HumanVision']

def components():
    result = []
    for folder in ROOTS:
        for path in (ROOT / folder).rglob('component.json'):
            item = json.loads(path.read_text(encoding='utf-8-sig'))
            for key in ('id', 'type', 'version', 'api_version', 'capabilities', 'dependencies', 'test_targets'):
                if key not in item: raise ValueError(f'{path}: missing {key}')
            if not path.with_name('README.md').is_file(): raise ValueError(f'{path}: missing README.md')
            result.append((path, item))
    result.sort(key=lambda pair: pair[1]['id'])
    ids = [item['id'] for _, item in result]
    if len(ids) != len(set(ids)): raise ValueError('Duplicate component id')
    return result

def render(items):
    lines = ['# Generated component catalog', '', 'Generated by tools/maintenance/generate_component_catalog.py. Do not edit.', '',
             '| ID / version | Type / ABI | Capabilities | Dependencies | Tests | README |', '|---|---|---|---|---|---|']
    for path, item in items:
        relative = path.parent.relative_to(ROOT).as_posix()
        cells = [item['id'] + ' / ' + item['version'], item['type'] + ' / ' + str(item['api_version']),
                 ', '.join(item['capabilities']), ', '.join(item['dependencies']), ', '.join(item['test_targets']),
                 f'[component](../../{relative}/README.md)']
        lines.append('| ' + ' | '.join(cells) + ' |')
        if item.get('exports'): lines.append('| exports: ' + ', '.join(item['exports']) + ' | | | | | |')
    return '\n'.join(lines) + '\n'

def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    expected = render(components())
    if args.check:
        if not CATALOG.exists() or CATALOG.read_text(encoding='utf-8') != expected: raise SystemExit('Component catalog stale; regenerate it')
    else:
        CATALOG.parent.mkdir(parents=True, exist_ok=True); CATALOG.write_text(expected, encoding='utf-8')
    print('Component catalog: PASS')

if __name__ == '__main__': main()
